apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud_storage-config
  namespace: cloud_storage
data:
  VAULTBOX_REDIS_URL: "redis://redis:6379/0"
  VAULTBOX_MINIO_ENDPOINT: "minio:9000"
  VAULTBOX_MINIO_ACCESS_KEY: "minio-prod-access"
  VAULTBOX_MINIO_SECRET_KEY: "minio-prod-secret"
  VAULTBOX_CELERY_BROKER_URL: "redis://redis:6379/1"
  VAULTBOX_CELERY_RESULT_BACKEND: "redis://redis:6379/2"
  VAULTBOX_CORS_ORIGINS: "https://app.cloud_storage.local,https://admin.cloud_storage.local"
  VAULTBOX_DEFAULT_STORAGE_QUOTA_BYTES: "5368709120"
  VAULTBOX_MAX_UPLOAD_SIZE_BYTES: "5368709120"
