apiVersion: v1
kind: Secret
metadata:
  name: cloud_storage-secrets
  namespace: cloud_storage
type: Opaque
stringData:
  postgres-password: cloud_storage-prod-password
  minio-access-key: minio-prod-access
  minio-secret-key: minio-prod-secret
  jwt-secret: jwt-prod-secret-change-me
