apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cloud_storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: cloud_storage
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud_storage-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: cloud_storage
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
